<?php
/**									ents_list_action1.php
 *
 */

$action='ents_list.php';

$table=$_POST['table'];
$title=$_POST['title'];
if(isset($_POST['bid'])){$bid=$_POST['bid'];}else{$bid='%';}
if(isset($_POST['catid'])){$catid=$_POST['catid'];}else{$catid=array();}
if(isset($_POST['ratvalue'])){$ratvalue=$_POST['ratvalue'];}else{$ratvalue='N';}
if(isset($_POST['newyid'])){$newyid=$_POST['newyid'];}else{$newyid='';}
$detail=$_POST['detail'];
$entrydate = $_POST['date'];

include('scripts/sub_action.php');

/********Check user has permission to edit************
$yid=$Student['NCyearActual']['id_db'];
$perm=getYearPerm($yid, $respons);
if($perm['w']!=1){
	print '<h5 class='warn'>You don't have the permissions to edit this page!</h5>'; exit;
	}
*/

if($sub=='Submit'){
	$current='student_view.php';
    $d_ncyear=mysql_query("SELECT DISTINCT ncyear FROM yeargroup JOIN student ON
		yeargroup.id=student.yeargroup_id WHERE student.id='$sid'");
    $ncyear=mysql_result($d_ncyear,0);

	if($bid=='' OR $bid=='%'){$bid='General';}
	$category='';
	for($c=0;$c<sizeof($catid);$c++){
	    $category=$category.$catid[$c].':'.$ratvalue.';';
		}

	if($table=='concerns'){
	    $d_ncyear=mysql_query("SELECT ncyear FROM yeargroup WHERE id='$newyid'");
	    $ncyear=mysql_result($d_ncyear,0);
		if(mysql_query("INSERT INTO $table SET student_id='$sid',
		detail='$detail', entrydate='$entrydate', ncyear='$ncyear',
		subject_id='$bid', category='$category', teacher_id='$tid'")){}
		else{$error[]=mysql_error();}
		$result[]='Comment recorded.';
		}
	elseif($table=='background'){
	    $d_ncyear=mysql_query("SELECT ncyear FROM yeargroup WHERE id='$newyid'");
	    $ncyear=mysql_result($d_ncyear,0);
		if(mysql_query("INSERT INTO $table SET student_id='$sid',
		detail='$detail', entrydate='$entrydate', ncyear='$ncyear',
		category='$category', teacher_id='$tid'")){}
		else{$error[]=mysql_error();}
		$result[]='Comment recorded.';
		}
	elseif($table=='incidents'){
		if(mysql_query("INSERT INTO $table SET student_id='$sid',
		detail='$detail', entrydate='$entrydate', ncyear='$ncyear',
		subject_id='$bid', category='$category',
		teacher_id='$tid'")){$result[]='Incident recorded.';}
		else{$error[]=mysql_error();}
		$footer='--'. '\r\n' .' 
		This message is confidential. It has been generated by ClaSS from an
		Incident Report posted to the system. You have received it
		because you are recorded as being responsible for either the
		pastoral or academic interests of this student. Please advise
		your ClaSS administrator if you believe you have received this
		email by mistake. Please delete this message from your system
		once it has been acted upon. Any unauthorized use or
		dissemination of this message in whole or in part is strictly
		prohibited.';

		$subject='Incident Report for '.$Student['Forename']['value']
				.' '.$Student['Surname']['value'].' ('. 
					$Student['RegistrationGroup']['value'].')'; 
		$message=$subject.'\r\n'.'Subject: '.$bid.'\r\n'.$detail.'\r\n'. 
				'Posted by '.$tid.'\r\n'.$footer;
		$recipients=findResponsibles($sid,$bid);
		}
	elseif($table=='exclusions'){
		$enddate = $_POST['date2'];
		$category=$_POST{'category'};
		if(mysql_query("INSERT INTO $table SET student_id='$sid',
		reason='$detail', startdate='$entrydate',
		enddate='$enddate', category='$category'")){}
		else{$error[]=mysql_error();}
		$result[]='Exclusion recorded.';
		}
	else{
		if(mysql_query("INSERT INTO $table SET student_id='$sid',
		detail='$detail', entrydate='$entrydate', ncyear='$ncyear',
		category='$category', subject_id='$bid', teacher_id='$tid'")){}
		else{$error[]=mysql_error();}
		$result[]='Entry recorded.';
		}

	if($recipients){
		if(sizeof($recipients)>0){
			$headers = 'From: ClaSS@'.$siteaddress . '\r\n' . 
				'Reply-To: noreply@'.$siteaddress . '\r\n' .
			    'X-Mailer: PHP/' . phpversion();

			foreach($recipients as $key => $recipient){
				$recipient['email']=strtolower($recipient['email']);
				if(mail($recipient['email'],$subject,$message,$headers)){
					$result[]='Email sent to '.$recipient['username'];}
				}
			}
		}
    $_SESSION{'Student'}=fetchStudent($sid);
	}

include('scripts/results.php');
include('scripts/redirect.php');
	
?>
