<?php
/*									incidents_list_action.php
 *
 */

$action='incidents_list.php';

$id=$_POST['id_db'];
$detail=$_POST['detail'];
$entrydate = $_POST['entrydate'];
if(isset($_POST['bid'])){$bid=$_POST['bid'];}else{$bid='%';}
if(isset($_POST['catid'])){$catid=$_POST['catid'];}else{$catid=array();}
if(isset($_POST['ratvalue'])){$ratvalue=$_POST['ratvalue'];}else{$ratvalue='N';}
if(isset($_POST['newyid'])){$newyid=$_POST['newyid'];}else{$newyid='';}

/********Check user has permission to edit************
$yid=$Student['NCyearActual']['id_db'];
$perm=getYearPerm($yid, $respons);
if($perm['w']!=1){
	print '<h5 class='warn'>You don't have the permissions to edit this page!</h5>'; exit;
	}
*/

include('scripts/sub_action.php');


	$ncyear=fetchNCYear($sid);	
	if($bid==''){$bid='%';}
	$category='';
	for($c=0;$c<sizeof($catid);$c++){
	    $category=$category . $catid[$c] . ':' . $ratvalue . ';';
		}

	if($id!=''){
		if(mysql_query("UPDATE incidents SET student_id='$sid',
		detail='$detail', entrydate='$entrydate', ncyear='$ncyear',
		subject_id='$bid', category='$category',
		teacher_id='$tid' WHERE id='$id'")){$result[]='Incident recorded.';}
		else{$error[]=mysql_error();}
	}
	else{
		if(mysql_query("INSERT INTO incidents SET student_id='$sid',
		detail='$detail', entrydate='$entrydate', ncyear='$ncyear',
		subject_id='$bid', category='$category',
		teacher_id='$tid'")){$result[]='Incident recorded.';}
		else{$error[]=mysql_error();}
	}
	$footer='--'. '\r\n' .' 
		This message is confidential. It has been generated by ClaSS from an
		Incident Report posted to the system. You have received it
		because you are recorded as being responsible for either the
		pastoral or academic interests of this student. Please advise
		your ClaSS administrator if you believe you have received this
		email by mistake. Please delete this message from your system
		once it has been acted upon. Any unauthorized use or
		dissemination of this message in whole or in part is strictly
		prohibited.';

	$subject='Incident Report for '.$Student['Forename']['value']
				.' '.$Student['Surname']['value'].' ('. 
					$Student['RegistrationGroup']['value'].')'; 
	$message=$subject.'\r\n'.'Subject: '.$bid.'\r\n'.$detail.'\r\n'. 
				'Posted by '.$tid.'\r\n'.$footer;
	$recipients=findResponsibles($sid,$bid);

	if($recipients){
		if(sizeof($recipients)>0){
			$headers=emailHeader();
			foreach($recipients as $key => $recipient){
					$recipient['email']=strtolower($recipient['email']);
					if(mail($recipient['email'],$subject,$message,$headers)){
						$result[]='Email sent to '.$recipient['username'];}
					}
			}
		}

$_SESSION{'Student'}=fetchStudent($sid);
include('scripts/results.php');
include('scripts/redirect.php');
	
?>
