<?php 
/**											install.php
 *	This is the run once install script.
 *	Creates the database and tables.
 *	Generates the script dbh_connect.php that is used as 
 *	an include by all other database connections.
 */

$hostname=$_POST['hostname'];
$username=$_POST['username'];
$oldpassword=$_POST['oldpassword'];
$password=$_POST['password'];
$password2=$_POST['password2'];
$schooldb=$_POST['school'];
?>

<html>
<head>
<meta http-equiv="Content-Script-Type" content="text/JavaScript" />
<meta name="copyright" content="Copyright 2002, 2003, 2004, 2005, 2006
	Stuart Thomas Johnson. All trademarks acknowledged. All rights reserved." />
<meta name="license" content="GNU General Public License version 2" />
</head>
<body>

<img name="sitelogo"  src="../images/orangelogo.png" style="width:120px;"/>
<h2>The (hopefully) ClaSS Results</h2>
<?php
	/*check the password*/
	if($password!=$password2){die('Mistake in matching the passwords. Please try again!');}

	/*this requires you have the PEAR:DB library installed*/
	/*ClaSS simply won't work without!*/
	require_once('DB.php');
	PEAR::setErrorHandling(PEAR_ERROR_DIE);
	$dsn="mysql://$username:$oldpassword@unix+$hostname";
	$dbh=DB::connect($dsn);
	$dbh->setFetchMode(DB_FETCHMODE_OBJECT);

	/*check db doesn't already exist*/
	$result=mysql_list_dbs();
	$exists='';
	while($row=mysql_fetch_array($result, MYSQL_NUM)) {
	    if($row[0]==$schooldb){$exists='yes';}
		}
	if($exists=='yes'){
		$selected=mysql_select_db($schooldb)
				or die('Could not select db '.$schooldb);
		$d_tables=mysql_query("SHOW TABLES;");
		while($row=mysql_fetch_row($d_tables)){
			$table=$row[0];
			if(mysql_query("DROP TABLE $table;")){
				}
			else{
				die('Failed! Could not drop old table '.$table. 
						 '<br />'.' '.mysql_error().'<br />');
				}
			}
		print 'Successfully dropped the tables from the old database.<br />';
		if(mysql_query("ALTER DATABASE $schooldb DEFAULT COLLATE
							utf8_general_ci CHARACTER SET utf8;")){}
		else{print 'WARNING: Did not have the priviliges to alter the
						character set to utf8!';}
		}
	elseif(mysql_query("CREATE DATABASE $schooldb DEFAULT CHARACTER SET
				utf8 COLLATE utf8_general_ci;")){
			print 'Successfully created new database: ';	
			print $schooldb.'<br />';
			$selected=mysql_select_db($schooldb) 
					or die('Could not select db '.$schooldb);
			}
	else{
			print 'Failed to create database '.$schooldb.'! <br />';
			exit;
			}

	if(mysql_query("GRANT ALL PRIVILEGES ON $schooldb.* TO
				class@localhost IDENTIFIED BY '$password'")){
			print 'Successfully granted privileges to MySQL user:class <br />';	
			}
		else {
			print 'WARNING! Failed with database privileges for class user!<br />'; 
			}

/* 	Create the core database tables */
	include('create_admin.php');
	$asswd=md5($password);
	mysql_query("INSERT INTO users (username, passwd, 
			forename,role,firstbookpref) VALUES ('administrator', 
			'$asswd', 'administrator','admin','admin')");
	$admin_uid=mysql_insert_id();

/*	Optional tables for the books */
	if(file_exists('create_markbook.php')){
		include('create_markbook.php');
		}
	if(file_exists('create_reportbook.php')){
		include('create_reportbook.php');
		}
	if(file_exists('create_infobook.php')){
		include('create_infobook.php');
		}

/* Write the database access file to the toplevel directory*/	
	$file=fopen ('../../dbh_connect.php', 'w');	
	if(!$file){
		echo '<p>Unable to open remote file for writing.</p>';
		echo '<p>Check that the toplevel class-site directory has 
			its permissions set to be writable by the webserver.</p>';
		exit;
		}
	
/* Lines to write to generate the dbh_connect.php script. */
      $string[0]="<?php /* 	auto-generated by ClaSS Install */";
      $string[1]="function &db_connect() {";
      $string[2]="	require_once 'DB.php';";
      $string[3]="	PEAR::setErrorHandling(PEAR_ERROR_DIE);";
	  $string[4]="	\$db_user = 'class';";
      $string[5]="	\$db_pass = '".$password."';";
      $string[6]="	\$db_host = '".$hostname."';";
      $string[7]="	\$db_name = '".$schooldb."';";
      $string[8]="	\$dsn = \"mysql://\$db_user:\$db_pass@unix+\$db_host/\$db_name\";";
      $string[9]="	\$db = DB::connect(\$dsn);";
      $string[10]="	\$db->setFetchMode(DB_FETCHMODE_OBJECT);";
      $string[11]="	return \$db;";
      $string[12]="	}";
      $string[13]="?>";

 	for($c=0; $c < sizeof($string); $c++){
		fputs ($file, $string[$c]."\n");
		}
	fclose ($file);

	if(mysql_query("FLUSH PRIVILEGES;")){
		print 'Flushed with success.<br />';
		}
?>

	<hr width=90%>
	<p>If all the above lines where successful, well done! 
	<br />Your ClaSS is ready for you.</p>

	<hr width=90%> <p>Point your browser at <a
	href="../index.php">ClaSS</a></p> <p>One administrator login has been
	automatically generated. </p> <p>Login with username=administrator
	to configure things.</p> <p>The password is the same 
	entered as the ClaSS Connection password on the previous form -
	you should change this at the first opportunity.</p>
	<p>If you are going to be repsonsible for the configuration and
	day-to-day running<br /> of this ClaSS install then refer to the
	ClaSS Administrators Guide for what to do next<br /> <button
	onClick="window.open('http://www.laex.org/class/docu.html', 'ClaSS
	Homepage');">ClaSS Documentation</button>
</p>

</body>
</html>
