<?php 
/**											install.php
 *	This is the run once install script.
 *	Creates the database and tables.
 *	Generates the script dbh_connect.php that is used as 
 *	an include by all other database connections.
 */

$hostname=$_POST['hostname'];
$username=$_POST['username'];
$oldpassword=$_POST['oldpassword'];
$password=$_POST['password'];
$password2=$_POST['password2'];
$schooldb=$_POST['school'];

require_once('../../school.php');
require_once('../classdata.php');
require_once('../lib/include.php');
require_once('../lib/eportfolio_functions.php');

?>

<html>
  <head>
	<meta http-equiv="Content-Script-Type" content="text/JavaScript" />
	<meta name="copyright" content="Copyright 2002 - 2016 Stuart Thomas Johnson. All trademarks acknowledged. All rights reserved." />
	<meta name="license" content="GNU General Public License version 2" />
	<link rel="stylesheet" type="text/css" href="../css/bookstyle.css" />
  </head>

  <body>


	<div class="externalbookframe">
	  <div class="content">
		<div class="center">
		  <div class="left">
			<?php print_string('hopefullyclassresults','install');?>
		  </div>
		  <div class="right">
			<div class="center"><?php print_string('yournew','install');?></div>
			<div class="center">
			<img name="sitelogo" 
			  onClick="window.open('../../index.html','ClaSS');"
			  src="../images/orangelogo.png" style="width:120px;cursor:pointer;"/>
			</div>
			<div class="center"><?php print_string('applicationsite','install');?></div>
		  </div>
	  <div class="left">
<?php
	/* check the password */
	if($password!=$password2){die('Mistake in matching the passwords. Please try again!');}


	/**
	 *  This requires you have the PEAR:DB library installed
	 *  ClaSS simply won't work without!
	 *
	 */
	require_once('DB.php');
	PEAR::setErrorHandling(PEAR_ERROR_DIE);
	$dsn="mysql://$username:$oldpassword@unix+$hostname";
	$dbh=DB::connect($dsn);
	$dbh->setFetchMode(DB_FETCHMODE_OBJECT);

	/* check db doesn't already exist */
	$result=mysql_list_dbs();
	$exists='';
	while($row=mysql_fetch_array($result, MYSQL_NUM)){
	    if($row[0]==$schooldb){$exists='yes';}
		}
	if($exists=='yes'){
		$selected=mysql_select_db($schooldb)
				or die('Could not select db '.$schooldb);
		$d_tables=mysql_query("SHOW TABLES;");
		while($row=mysql_fetch_row($d_tables)){
			$table=$row[0];
			if(mysql_query("DROP TABLE $table;")){
				}
			else{
				die('Failed! Could not drop old table '.$table. 
						 '<br />'.' '.mysql_error().'<br />');
				}
			}
		print 'Successfully dropped the tables from the old database.<br />';
		if(mysql_query("ALTER DATABASE $schooldb DEFAULT COLLATE
							utf8_general_ci CHARACTER SET utf8;")){}
		else{print 'WARNING: Did not have the priviliges to alter the character set to utf8!';}
		}
	elseif(mysql_query("CREATE DATABASE $schooldb DEFAULT CHARACTER SET
				utf8 COLLATE utf8_general_ci;")){
			print 'Successfully created new database: ';
			print $schooldb.'<br />';
			$selected=mysql_select_db($schooldb) 
					or die('Could not select db '.$schooldb);
			}
	else{
			print 'Failed to create database '.$schooldb.'! <br />';
			exit;
			}

	if(mysql_query("GRANT ALL PRIVILEGES ON $schooldb.* TO class@localhost IDENTIFIED BY '$password'")){
			print 'Successfully granted privileges to MySQL user:class <br />';	
			}
		else{
			print 'WARNING! Failed with database privileges for class user!<br />'; 
			}


	/* 	Create the core database tables */
	$errorno=execute_sql_file('create_admin.sql');
	if($errorno==0){
		/* Setup an administrator's account. */ 
		$asswd=md5($password);
		mysql_query("INSERT INTO users (username, passwd, 
			forename,role,firstbookpref) VALUES ('administrator', 
			'$asswd', 'administrator','admin','admin')");
		$admin_uid=mysql_insert_id();
		mysql_query("INSERT INTO section (name,sequence,teacher_id) 
				VALUES ('Whole School','1','');");
		}
	else{
		die('Could not create core db tables for '.$schooldb);
		}

	/* Create the rest of the tables. */
	$books=array('markbook','reportbook','infobook','register','orderbook','transport');
	foreach($books as $book){
		$errorno=execute_sql_file('create_'.$book.'.sql');
		if(!$errorno==0){
			die('Could not create db tables for '.$book);
			}
		}


	/* Write the database access file to the toplevel directory*/	
	$file=fopen ('../../dbh_connect.php', 'w');	
	if(!$file){
		echo '<p>Unable to open remote file for writing.</p>';
		echo '<p>Check that the toplevel class-site directory has 
			its permissions set to be writable by the webserver.</p>';
		exit;
		}
	
	/* Lines to write to generate the dbh_connect.php script. */
      $string[0]="<?php /* 	auto-generated by ClaSS Install */";
      $string[1]="function &db_connect(\$con=true,\$db_name = '".$schooldb."') {";
      $string[2]="	require_once 'DB.php';";
      $string[3]="	PEAR::setErrorHandling(PEAR_ERROR_DIE);";
	  $string[4]="	\$db_user = 'class';";
      $string[5]="	\$db_pass = '".$password."';";
      $string[6]="	\$db_host = '".$hostname."';";
      $string[7]="	\$dsn = \"mysql://\$db_user:\$db_pass@unix+\$db_host/\$db_name\";";
      $string[8]="	if(\$con){";
      $string[9]="	  \$db = DB::connect(\$dsn);";
      $string[10]="	  \$db->setFetchMode(DB_FETCHMODE_OBJECT);";
      $string[11]="	  return \$db;";
      $string[12]="	  }";
      $string[13]="	else{";
	  $string[14]="	  return \$dsn;";
      $string[15]="	  }";
      $string[16]="?>";

 	for($c=0; $c < sizeof($string); $c++){
		fputs($file,$string[$c]."\n");
		}
	fclose($file);

	if(mysql_query("FLUSH PRIVILEGES;")){
		print 'Flushed with success.<br />';
		}
?>
	  </div>
	  <div class="left">
<?php
	if($CFG->eportfolio_dataroot=='' or !is_writable($CFG->eportfolio_dataroot)){
		die('The dataroot directory defined in school.php ( '. 
			$CFG->eportfolio_dataroot.' ) is not writable by the Apache user.');
		}
	else{
		//make_portfolio_directory('cache/phpThumb',true);
		make_portfolio_directory('cache/files',true);
		make_portfolio_directory('cache/reports',true);
		make_portfolio_directory('cache/images',true);
		make_portfolio_directory('sessions',true);
		}

?>
	  </div>
		  <div class="left">
			<hr width="100%" />
			  <p>If all the above lines where successful, well done!</p>
			  <p>Your ClaSS is ready for you; click on the link to the right.</p>
			  <p>If you've encountered a problem then consult the
				Install-FAQ and README both available from the documentation
				link.</p>
			  <hr width="100%" />
		  </div>

		  <div class="left">
			<p>One administrator login has been automatically generated.
			</p>

			<p>Login with username=administrator to configure things.
			</p>

			<p>The password is the same entered as the ClaSS Connection
			  password on the previous form - you should change this at
			  the first opportunity.
			</p>
		
			<p>If you are going to be repsonsible for the configuration
			  and day-to-day running of this ClaSS install then
			  refer to the ClaSS Administrators' Guide for what to do
			  next, available from the documentation link to the right. 
			</p>
		  </div>

		  <div class="right">	
			<div class="center"><?php print_string('wherenext','install');?></div>
			<div class="center">
			<button class="install"
			  onClick="window.open('http://www.laex.org/class/docu.html',
			  'ClaSS Homepage');">ClaSS Documentation</button>
			</div>
			<div class="center"><?php print_string('forhelpandsupport','install');?></div>
		  </div>

		</div>
	  </div>
  </body>
</html>
