<?php
/**						scripts/sub_action.php
 *
 * returns the value of the submit button in $sub
 * and redirects if $sub='cancel' or $sub is blank
 * in the latter the event must have been generated by an onChange 
 * from a form field and not from a button meaning this just
 * simply reloads the current page (with some new post value)
 */

$sub=$_POST['sub'];
if($sub=='Cancel'){
	if($cancel==''){$action='';$choice='';}
	else{$action=$cancel;}
	include('scripts/redirect.php');
	exit;
	}
elseif($sub==''){
	//$result[]=$newcomid;
	//include('scripts/results.php');
	include('scripts/redirect.php');
	exit;
	}
?>